---
openapi: 3.0.2
info:
  title: Spec
  version: 0.0.1
  description: API definition of spec
  contact:
    name: creator's name
    url: 'http://creator.homepage.address'
    email: creator@creator.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
paths:
  /specs:
    summary: Global operations on specs
    get:
      tags:
        - specs
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Spec'
              examples:
                specs_json:
                  value:
                    - id: 1
                      spec: A string
                      phoneColor: A string
                      phoneType: A string
                      image: value
                      manufacturer: value
          description: Get list of specs
      operationId: GetSpec
      summary: Get list of specs
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Spec'
            examples:
              '1':
                value:
                  id: 1
                  spec: A string
                  phoneColor: A string
                  phoneType: A string
                  image: value
                  manufacturer: value
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spec'
              examples:
                '1':
                  value:
                    id: 1
                    spec: A string
                    phoneColor: A string
                    phoneType: A string
                    image: value
                    manufacturer: value
          description: Changed Spec
      operationId: Post Spec
      summary: Post Spec
  '/specs/{id}':
    summary: Specific operation on specs
    get:
      parameters:
        - examples:
            '1':
              value: 1
          name: id
          description: Spec name
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spec'
              examples:
                '1':
                  value:
                    id: 1
                    spec: A string
                    phoneColor: A string
                    phoneType: A string
                    image: value
                    manufacturer: value
          description: specs with specified id
      operationId: GetSpecById
      summary: Get Spec by id
      description: Get Spec by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Spec'
            examples:
              '1':
                value:
                  id: 1
                  spec: A string
                  phoneColor: A string
                  phoneType: A string
                  image: value
                  manufacturer: value
        required: true
      parameters:
        - examples:
            '1':
              value: 1
          name: id
          description: Spec name
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spec'
              examples:
                '1':
                  value:
                    id: 1
                    spec: A string
                    phoneColor: A string
                    phoneType: A string
                    image: value
                    manufacturer: value
          description: Changed Spec
      operationId: PatchSpec
      summary: Patch existing Spec
    parameters:
      - name: id
        description: Spec id
        schema:
          type: integer
        in: path
        required: true
components:
  schemas:
    Spec:
      title: Root Type for Spec
      description: The root of the Spec type's schema.
      type: object
      properties:
        id:
          description: id of this Spec
          type: integer
        spec:
          description: spec of this Spec
          type: string
        phoneColor:
          description: phoneColor of this Spec
          type: string
        phoneType:
          description: phoneType of this Spec
          type: string
        image:
          description: image of this Spec
          type: string
        manufacturer:
          description: manufacturer of this Spec
          type: string
tags:
  - name: Spec
    description: Spec resource
